import re

def extract_blocks(filename):
    with open(filename, 'r', encoding='utf-8', errors='replace') as f:
        data = f.read()
    # Find all timestamp delimiters (hh:mm:ss:)
    matches = list(re.finditer(r'\d{2}:\d{2}:\d{2}:', data))
    blocks = []
    prev_end = 0
    for m in matches:
        start = m.start()
        block = data[prev_end:start]
        block = block.strip()
        if block:
            blocks.append(block)
        prev_end = m.end()
    final_block = data[prev_end:]
    final_block = final_block.strip()
    if final_block:
        blocks.append(final_block)
    return blocks

def format_c_array(block, name):
    # Remove all newlines and carriage returns for flat string
    safe_block = block.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '').replace('\r', '')
    return f'char {name}[] = "{safe_block}";'

def main(input_file, output_header):
    blocks = extract_blocks(input_file)
    c_blocks = []
    block_names = []
    for idx, block in enumerate(blocks):
        cname = f'block{idx+1}'
        c_blocks.append(format_c_array(block, cname))
        block_names.append(cname)
    with open(output_header, 'w', encoding='utf-8') as h:
        h.write('// Autogenerated blocks from input file\n\n')
        for line in c_blocks:
            h.write(line + '\n')
        # Auto-generate pointer array for iteration
        h.write('\nchar* blocks[] = {\n    ' + ',\n    '.join(block_names) + '\n};\n')
        h.write('#define NUM_BLOCKS (sizeof(blocks)/sizeof(blocks[0]))\n')

if __name__ == "__main__":
    main("COM-x1-RS485.txt", "blocks.h")
