/**
 * Elevator Control System - 150 Block Arrays
 * ============================================
 * 
 * Each block is a single frame repeated 10 times (360 chars total per block)
 * Frame structure: 36 chars each ([H + data + \n + inputs + \x1B)
 * 
 * Generated with random variations of:
 *   - Car IDs: A, B, C
 *   - Directions: -, +, a-z, 0-9
 *   - Levels: 00-31
 *   - OCSS states: 43 different codes
 *   - MCSS states: 12 different codes
 *   - Door states: [], ][, <>, ><
 *   - System inputs: 120+ different codes
 */

#ifndef ELEVATOR_BLOCKS_H
#define ELEVATOR_BLOCKS_H

char block1[] =
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B"
"[HBa04 WCO EW []<>\n^SGS CTO UIB L30\x1B";

char block2[] =
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B"
"[HBw16 CTL CR <><>\nFAN ^DCL EDB TDC\x1B";

char block3[] =
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B"
"[HBk17 EPC FR ][[]\n^MDD ACC ERO PKS\x1B";

char block4[] =
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B"
"[HC510 NOR ES []><\nUIB EDP ^GSM LWO\x1B";

char block5[] =
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B"
"[HAa13 DTO FR ][[]\nDCL LRD EQW ^WDO\x1B";

char block6[] =
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B"
"[HCa29 WCO RL ][[]\nWDO ^WDC HCO ISS\x1B";

char block7[] =
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B"
"[HBv03 EPW RS <>[]\nEQS TCI ^DOS ESH\x1B";

char block8[] =
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B"
"[HCa02 INS EW ][><\nPKG ^TDO ETS HCH\x1B";

char block9[] =
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B"
"[HBx02 NOR FR ][><\n^WDC FAN EFO CFB\x1B";

char block10[] =
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B"
"[HBz15 IDL ST ><[]\nERO TCB ^DOL 2TH\x1B";

char block11[] =
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B"
"[HBx16 EPW IN ][><\nDFD ^DCB PDD DIB\x1B";

char block12[] =
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B"
"[HBe18 CBP ST <><>\n^SDB SGS CTL ESH\x1B";

char block13[] =
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B"
"[HAo05 MIT ST ][<>\nAEF ^DOB ETS GCO\x1B";

char block14[] =
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B"
"[HB712 EFO IN <>[]\n2LV LNS ^MDD EQ1\x1B";

char block15[] =
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B"
"[HC506 ESB SR <>][\nWDO ^TDC DES 1LV\x1B";

char block16[] =
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B"
"[HAr17 CBP RL ][<>\nRTB ^MDD DDS LNS\x1B";

char block17[] =
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B"
"[HAb24 HBP NR []][\nRRB ^DOL PKS DCB\x1B";

char block18[] =
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B"
"[HBe12 CHC SR ][<>\n^WDO L30 L50 ASL\x1B";

char block19[] =
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B"
"[HBe05 WCO SR [][]\nGCB LNS ^TDO 2LS\x1B";

char block20[] =
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B"
"[HA603 NOR ES ><][\nCCB L50 NUG ^TDO\x1B";

char block21[] =
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B"
"[HBj07 ATT EF <><>\nEQW ^WDO EQ1 EQR\x1B";

char block22[] =
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B"
"[HAh05 ANS ST ><[]\nDDS ^SGS 2SE CTO\x1B";

char block23[] =
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B"
"[HB024 LNS ES []><\n^SDB HAD 2TH NAV\x1B";

char block24[] =
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B"
"[HA828 EHS EF <><>\n^GSM ISP CTL EFO\x1B";

char block25[] =
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B"
"[HAs00 WCO EW ><<>\nLNS HFA PKS ^EDP\x1B";

char block26[] =
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B"
"[HBv30 CBP IN ][><\nHFA CFS EDP ^DOB\x1B";

char block27[] =
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B"
"[HCe00 EHS ST ][[]\nACH ESH HCH ^ISS\x1B";

char block28[] =
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B"
"[HCy30 HBP IN []][\n^FAN FAN ACH EFK\x1B";

char block29[] =
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B"
"[HCc10 EFS ST ><><\n^DCL LNS TCB XEF\x1B";

char block30[] =
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B"
"[HAj25 REI SR ><][\nRRB ^DOB NUG ISS\x1B";

char block31[] =
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B"
"[HCj08 EFS ID ><][\n^GCB CRC 1EF ADB\x1B";

char block32[] =
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B"
"[HAs15 EPW FR [][]\nCOC WDO ^WDC EQ1\x1B";

char block33[] =
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B"
"[HAp22 DLM SR []><\nEQ2 NOR ^DOB GDS\x1B";

char block34[] =
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B"
"[HAr06 EFO EF <>[]\n^TDC 2LV 2TH DDS\x1B";

char block35[] =
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B"
"[HA819 DHB FR <>][\n^DOB COC ACH ISP\x1B";

char block36[] =
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B"
"[HAr26 EMT CR [][]\nASL PKS NUD ^LRD\x1B";

char block37[] =
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B"
"[HB621 WCS EF <>[]\n1LS L30 DFC ^DOS\x1B";

char block38[] =
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B"
"[HCv28 ARD SR ][[]\n1TH 1LV PKG ^LRD\x1B";

char block39[] =
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B"
"[HA313 EFS EF []<>\nPKG GCB ^DCB EFO\x1B";

char block40[] =
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B"
"[HAb23 EPR RS <><>\nL30 ^DHB 2LV 1LS\x1B";

char block41[] =
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B"
"[HAe12 EQR SR <><>\n2LV EFB ^DCL EQ2\x1B";

char block42[] =
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B"
"[HAp02 GCB SR <><>\n^DCB PDD TDC HCO\x1B";

char block43[] =
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B"
"[HAm04 DCS RL <>><\nTCB TCI ^WDC CFB\x1B";

char block44[] =
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B"
"[HB128 MIT ID ><[]\n^DOS HAD CTL LWO\x1B";

char block45[] =
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B"
"[HAk22 ACP ID [][]\n2EF EDB ^DOB 2LS\x1B";

char block46[] =
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B"
"[HA719 EHS ID ][][\n^WDC TDO EQR LWX\x1B";

char block47[] =
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B"
"[HBc10 DCP RL ][[]\nEDP ^TDC HTS NAV\x1B";

char block48[] =
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B"
"[HCn30 EPC FR []><\nISS ^SGS GDS GSM\x1B";

char block49[] =
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B"
"[HBa04 INS EF []][\nDCL CTL ^LRD CFS\x1B";

char block50[] =
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B"
"[HBb05 INS ES ][[]\n2EF COC ^LRD FAN\x1B";

char block51[] =
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B"
"[HCc16 CTL EW [][]\nEQ2 CFB ^ISS 2TH\x1B";

char block52[] =
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B"
"[HCs21 PRK ID <>][\nDRD ACH ^FAN TDO\x1B";

char block53[] =
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B"
"[HAe22 ROT ST ><<>\n^FAN ASL XEF GCB\x1B";

char block54[] =
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B"
"[HBk00 REI ES []<>\nSGS ISP 2EF ^FAN\x1B";

char block55[] =
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B"
"[HBy04 NAV ES []][\n^GCB ROT ETS EQS\x1B";

char block56[] =
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B"
"[HBl12 EPC ES ][><\nEFB DRD ^DOS CCB\x1B";

char block57[] =
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B"
"[HBy07 DLM ST ][[]\nHTS ^TDC MDD EQW\x1B";

char block58[] =
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B"
"[HCn30 PRK FR []][\n^MDD AEF 2TH 2LS\x1B";

char block59[] =
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B"
"[HAn24 DHB EW ><><\n^EDP 2LV RRB DHB\x1B";

char block60[] =
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B"
"[HBw01 NAV NR <>><\nHTS ^GCB ROT CTL\x1B";

char block61[] =
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B"
"[HBz10 DTO SR ][[]\nPKG 1TH ^WDO NAV\x1B";

char block62[] =
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B"
"[HBm04 WCS EW ][[]\n^DOS ACC CHC GSM\x1B";

char block63[] =
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B"
"[HAy16 EPC RS <>][\nPKG ^MDD 1LV ROT\x1B";

char block64[] =
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B"
"[HCk11 EPW ST <>][\nEFO ^MDD EFK ISP\x1B";

char block65[] =
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B"
"[HCr02 DHB RS ><><\nTDC ^TDO L30 1TH\x1B";

char block66[] =
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B"
"[HC-04 DTC SR [][]\nCOC ^DOB ERO ACH\x1B";

char block67[] =
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B"
"[HCt20 ACP ID ][<>\nISS 2TH NOR ^SDB\x1B";

char block68[] =
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B"
"[HCm23 ANS EF []><\nCCB ^SDB LNS EDP\x1B";

char block69[] =
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B"
"[HBe04 REI ES ][][\n^ISS DDS ESK L30\x1B";

char block70[] =
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B"
"[HBd31 REI FR ][><\n2SE ^WDO EQS NAV\x1B";

char block71[] =
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B"
"[HCq14 COR RL ><<>\nCTL PKG ^WDO UIB\x1B";

char block72[] =
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B"
"[HCr03 ISC IN ][][\n^DOB COC HCH ISS\x1B";

char block73[] =
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B"
"[HB-03 DTC SR <><>\n^DCB SDB 2LV NUD\x1B";

char block74[] =
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B"
"[HBk28 EFS RS <>][\n^SDB COC LWO PDD\x1B";

char block75[] =
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B"
"[HB206 ROT NR []><\nTCI EQW ^ISS LRD\x1B";

char block76[] =
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B"
"[HCe08 HAD NR <>><\n^DOB ERO DHB PKS\x1B";

char block77[] =
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B"
"[HBe31 NAV FR <>><\n^TDC GSI GDS 1TH\x1B";

char block78[] =
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B"
"[HA-18 ROT RS ][<>\nNRF ASL ISS ^FAN\x1B";

char block79[] =
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B"
"[HBt14 PKS CR ><<>\nHFA ^DOB GCB HAD\x1B";

char block80[] =
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B"
"[HB402 INS ID [][]\nLWO ^WDO EDP COC\x1B";

char block81[] =
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B"
"[HCu17 DCP RL []<>\n^DOB EQ2 CHC DFC\x1B";

char block82[] =
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B"
"[HCb31 EFO SR []][\nCFB TCI 2TH ^DCB\x1B";

char block83[] =
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B"
"[HBc01 IDL CR ][<>\nRTB ^TDO ESK TCB\x1B";

char block84[] =
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B"
"[HCa16 DBF ID ][<>\n1LS MDD ^GCB ESH\x1B";

char block85[] =
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B"
"[HCv20 DCS ES <>[]\nISS ^TDC RTB DFD\x1B";

char block86[] =
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B"
"[HC+25 OLD ST ][<>\nEQR RTB EFO ^MDD\x1B";

char block87[] =
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B"
"[HA-10 EPR ST <>[]\nEDP GCB ^DCL ISS\x1B";

char block88[] =
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B"
"[HBf12 PKS EW <>><\nHCH ^WDO GSI AEF\x1B";

char block89[] =
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B"
"[HCj21 CBP CR []<>\nDDS SGS ^DOS ASL\x1B";

char block90[] =
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B"
"[HC527 EPW ID <><>\nEQR TCB ^DOS CHC\x1B";

char block91[] =
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B"
"[HA+12 DHB RS ][][\nRTB DFD CRC ^WDO\x1B";

char block92[] =
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B"
"[HAz08 COR EW ][[]\nLWO ACH ^LRD ESK\x1B";

char block93[] =
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B"
"[HB118 ARD FR []><\nFAN ^TDO 2LV PDD\x1B";

char block94[] =
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B"
"[HAe05 HAD FR <>[]\nMDD ^EDP GCB NAV\x1B";

char block95[] =
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B"
"[HAu14 EQO EF [][]\nEQ2 ^TDC FAN LWX\x1B";

char block96[] =
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B"
"[HBk22 PRK EW <>[]\nEQS EFK L50 ^LRD\x1B";

char block97[] =
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B"
"[HA509 CTL RS []<>\n^GCB XEF L30 NUG\x1B";

char block98[] =
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B"
"[HCh05 EFS ST <>><\nLWX ESH CCT ^SDB\x1B";

char block99[] =
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B"
"[HBc10 EPR EF []><\nDIB DDS XEF ^ISS\x1B";

char block100[] =
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B"
"[HCo04 EFS EW ><<>\nNUD L30 1EF ^WDC\x1B";

char block101[] =
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B"
"[HA617 INS RS <>[]\nEQS ^TDC GSM XEF\x1B";

char block102[] =
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B"
"[HAc15 ARD SR []><\nEQ2 ^DOB FAN LRD\x1B";

char block103[] =
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B"
"[HAq16 ESB RS ><><\n^SDB WDO BRK CTC\x1B";

char block104[] =
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B"
"[HBk19 LNS ST []<>\nEFK ^TDC DDS HFA\x1B";

char block105[] =
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B"
"[HBq05 PRK SR ><[]\nNUG ^EDP TDC HCO\x1B";

char block106[] =
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B"
"[HBk05 ARD CR <>><\n2LV ^TDC ISP DDS\x1B";

char block107[] =
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B"
"[HCj09 LNS NR ><[]\n^DCB DCL EQ1 ESK\x1B";

char block108[] =
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B"
"[HAt23 EPR RL <>><\nESK ^WDC CCB 2LS\x1B";

char block109[] =
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B"
"[HCe27 REI SR [][]\n^MDD DFD PKS CRC\x1B";

char block110[] =
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B"
"[HCh11 HAD RS <>><\n^DHB SDB 1LS 2TH\x1B";

char block111[] =
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B"
"[HCd18 DTC EW []][\nNUG LWX 2SE ^DOS\x1B";

char block112[] =
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B"
"[HCz31 ACP EW [][]\n^WDC MDD EQ2 IST\x1B";

char block113[] =
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B"
"[HCf24 CTL RL ><][\nL30 GCB FAN ^DCL\x1B";

char block114[] =
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B"
"[HC001 ESB IN []><\nCFB HFA ETS ^GCB\x1B";

char block115[] =
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B"
"[HBg15 LNS RS ><][\nCFB ^DCL COC FAN\x1B";

char block116[] =
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B"
"[HAb04 ROT SR [][]\nETS BRK EQW ^TDO\x1B";

char block117[] =
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B"
"[HAt11 LNS ES ][][\nLWX DES ^DOB EDB\x1B";

char block118[] =
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B"
"[HB423 INI CR [][]\n^GSM 2SE NUG LWO\x1B";

char block119[] =
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B"
"[HCj18 DTC IN <>[]\n2LV PDD ^DHB ESH\x1B";

char block120[] =
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B"
"[HA314 EPW ST ><><\nDCB DCB ^SGS WDC\x1B";

char block121[] =
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B"
"[HAb22 LNS CR ><><\nACC ^DOL LNS COC\x1B";

char block122[] =
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B"
"[HAb18 NOR EF []<>\nSDB EQR GDS ^GSM\x1B";

char block123[] =
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B"
"[HCj18 NOR RL ><[]\nL30 CTL TCB ^DOL\x1B";

char block124[] =
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B"
"[HAc30 CBP FR ][[]\nHCH HTS 2EF ^DHB\x1B";

char block125[] =
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B"
"[HC809 HAD IN <>[]\nDRD ^FAN EQ2 NUG\x1B";

char block126[] =
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B"
"[HBb22 EHS CR [][]\nNUD NUD ^DHB PKG\x1B";

char block127[] =
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B"
"[HCu20 EHS RS <><>\nLWO LWO LRD ^LRD\x1B";

char block128[] =
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B"
"[HAi07 CHC EW ][><\nTCI CTC ^MDD EQ2\x1B";

char block129[] =
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B"
"[HBa20 IDL ST ><><\nCTC HTS 2LV ^EDP\x1B";

char block130[] =
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B"
"[HCb01 ARD NR []][\nTCB GSI EFO ^DOS\x1B";

char block131[] =
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B"
"[HB820 PKS IN ><[]\n^DOL EQR TCI 1EF\x1B";

char block132[] =
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B"
"[HAu13 ARD RL ][[]\nHAD NUG ^DHB DHB\x1B";

char block133[] =
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B"
"[HBn26 COR ST []][\nL30 ^EDP CTL ETS\x1B";

char block134[] =
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B"
"[HAs26 LNS NR ][><\nDFC TDC ^WDC PKS\x1B";

char block135[] =
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B"
"[HA728 ROT ST []][\n2EF HCO CTO ^FAN\x1B";

char block136[] =
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B"
"[HCt29 EPW NR <>><\nLRD ^SDB L50 1LV\x1B";

char block137[] =
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B"
"[HC122 DTC SR ><[]\nDCB ETS EQS ^TDO\x1B";

char block138[] =
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B"
"[HCt03 CTL EW []><\nCFS EFO EQ2 ^SGS\x1B";

char block139[] =
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B"
"[HAx04 HAD CR ][[]\n^FAN ISP COC SGS\x1B";

char block140[] =
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B"
"[HCr07 INS CR []><\n^GCB RTB PKS WDC\x1B";

char block141[] =
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B"
"[HC-16 ROT RL ][][\n^FAN LWX WDO DRD\x1B";

char block142[] =
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B"
"[HAs02 ACP CR <><>\nBRK CTO CTO ^DOB\x1B";

char block143[] =
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B"
"[HBy23 DBF CR <>[]\n^LRD 1EF LWX 2LS\x1B";

char block144[] =
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B"
"[HCn28 DBF ES ][><\nRRB FAN RTB ^SGS\x1B";

char block145[] =
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B"
"[HAx19 GCB ST ><<>\n^DCL EDP BRK PDD\x1B";

char block146[] =
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B"
"[HAv20 CBP RS <><>\nLNS CTL ROT ^DCB\x1B";

char block147[] =
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B"
"[HBl17 EPC FR ][<>\nHTS ^TDO TCI DHB\x1B";

char block148[] =
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B"
"[HCf04 EMT NR ][][\nPDD CCB 2SE ^DOL\x1B";

char block149[] =
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B"
"[HAx15 CBP FR ][<>\nHTS DIB ISS ^DCL\x1B";

char block150[] =
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B"
"[HAo16 IDL RL <>><\nGSI DCL MDD ^FAN\x1B";

// Pointer table to all blocks
char *blocks[] = {
    block1, block2, block3, block4, block5, 
    block6, block7, block8, block9, block10, 
    block11, block12, block13, block14, block15, 
    block16, block17, block18, block19, block20, 
    block21, block22, block23, block24, block25, 
    block26, block27, block28, block29, block30, 
    block31, block32, block33, block34, block35, 
    block36, block37, block38, block39, block40, 
    block41, block42, block43, block44, block45, 
    block46, block47, block48, block49, block50, 
    block51, block52, block53, block54, block55, 
    block56, block57, block58, block59, block60, 
    block61, block62, block63, block64, block65, 
    block66, block67, block68, block69, block70, 
    block71, block72, block73, block74, block75, 
    block76, block77, block78, block79, block80, 
    block81, block82, block83, block84, block85, 
    block86, block87, block88, block89, block90, 
    block91, block92, block93, block94, block95, 
    block96, block97, block98, block99, block100, 
    block101, block102, block103, block104, block105, 
    block106, block107, block108, block109, block110, 
    block111, block112, block113, block114, block115, 
    block116, block117, block118, block119, block120, 
    block121, block122, block123, block124, block125, 
    block126, block127, block128, block129, block130, 
    block131, block132, block133, block134, block135, 
    block136, block137, block138, block139, block140, 
    block141, block142, block143, block144, block145, 
    block146, block147, block148, block149, block150

};

#define BLOCKS_COUNT 150
#define BLOCK_FRAME_REPEATS 10
#define SINGLE_FRAME_SIZE 36
#define BLOCK_SIZE (SINGLE_FRAME_SIZE * BLOCK_FRAME_REPEATS)

#endif // ELEVATOR_BLOCKS_H
